
/**************************************************************
 *	
 *	GameSong, 8 bit, 11025Hz,
 *	1 channel, 195382 bytes/channel
 *	Total Size: 1 * 195382 + 4 (header) = 195426 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Jasmine\Google Drive\2016\CS_2261\Sublime\LAB10_JasmineBrown\LAB10_Sound\GameSong.wav
 *	Time-stamp: Wed Mar 16 16:48:44 2016
 *	
 **************************************************************/

#ifndef __GAMESONGH__
#define __GAMESONGH__

#define GAMESONGFREQ 11025
#define GAMESONGLEN 195382

extern const unsigned char GameSong[195382];

#endif /* __GAMESONGH__ */
