
/**************************************************************
 *	
 *	StartSFX, 8 bit, 11025Hz,
 *	1 channel, 127296 bytes/channel
 *	Total Size: 1 * 127296 + 4 (header) = 127340 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Jasmine\Google Drive\2016\CS_2261\Sublime\LAB10_JasmineBrown\LAB10_Sound\StartSFX.wav
 *	Time-stamp: Wed Mar 16 16:47:06 2016
 *	
 **************************************************************/

#ifndef __STARTSFXH__
#define __STARTSFXH__

#define STARTSFXFREQ 11025
#define STARTSFXLEN 127296

extern const unsigned char StartSFX[127296];

#endif /* __STARTSFXH__ */
