
/**************************************************************
 *	
 *	TitleSong, 8 bit, 11025Hz,
 *	1 channel, 447027 bytes/channel
 *	Total Size: 1 * 447027 + 4 (header) = 447071 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Jasmine\Google Drive\2016\CS_2261\Sublime\LAB10_JasmineBrown\LAB10_Sound\TitleSong.wav
 *	Time-stamp: Wed Mar 16 16:50:49 2016
 *	
 **************************************************************/

#ifndef __TITLESONGH__
#define __TITLESONGH__

#define TITLESONGFREQ 11025
#define TITLESONGLEN 447027

extern const unsigned char TitleSong[447027];

#endif /* __TITLESONGH__ */
